= Red Hat JBoss BPM Suite & Entando Client Onboarding FSI Demo

A _Client Onboarding_ FSI Demo, developed in Red Hat JBoss BPM Suite and Entando, running on OpenShift.

*TODO*: Insert link to introduction video on Youtube.

== Use case

*TODO*: Describe the use-case.


== Running on OpenShift

This demo runs both on local installations of OpenShift Origin and OpenShift Container Platform,
as well as OpenShift Enterprise, OpenShift Dedicated and OpenShift Online instances.

A provisioning script has been provided which fully automates the installation of this demo. The only prerequisit is a local `oc` client. The
demo is installed in the OpenShift environment to which the `oc` client is connected.


=== Prerequisites

. Install https://www.openshift.org/download.html[the oc client tools].

. Login into the OpenShift in which the demo needs to be provisioned. Depending on the installation you can login with:
.. `oc login <url>`: The `oc` client will ask for a username and password.
.. `oc login <url> <toke>`: The provided token is used for authentication.


NOTE: To copy-paste the login command and token, go to your OpenShift web console and look for _Help_ > _Command line tools_.

=== Install demo

Use the provision scripts to setup, configure, build and deploy the demo on OpenShift:

```
./openshift/provision.sh setup client-onboarding
```


=== Delete the OpenShift application and project

```
./openshift/provision.sh delete client-onboarding
```

=== Run the demo

*TODO*: Describe how to run the demo
